# Generated by Django 6.0.5 on 2026-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('char_class', models.CharField(max_length=50)),
            ],
        ),
    ]
