# Generated by Django 6.0.5 on 2026-05-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
